language: java
jdk:
- oraclejdk8

script:
- ./gradlew build --stacktrace
after_success:
  - gradle/deploy_snapshot.sh
branches:
  except:
  - gh-pages
notifications:
  email: false
sudo: false
cache:
  directories:
  - $HOME/.gradle
env:
  global:
    secure: 0kly8hq3sAQQP/xr8/2HRHnTeFj349He+WNmTcQD5eOWkBJ9n5/7KfG8qC+iUEpy0geSfo9MVzcSz9smw3mvVgnW8FnjTILUIu6t2l+EGNd4SbI+vEgpVR77SerMg8eCgNgUJxoU52XkytnVzE6ZWmsGDd94pDWIFymedSOqeuZCL23WLIqyfH+tGPHmQAT28kwY9DB3j3bp688UVHo/B/BUVsJEy9/W9OtVbnASNIDR/2CxgKLIdpMjSH8NCjVVMLfx+SGJlapErLQhr5Cc7znq8WNijuU2N8Oc0eJ+enyRyO44shyORPRGi7X0jdUl78ShxraIDya2qwzqUzAwTBz4mGVJn6uO/QnVyk6ZmIO2Ah6l0TVy1kaeLCOaLJwwase1GM55VHjkNAjr8iptSU+AFhF2bR2nRGrpCGBnOiT7NcybUZ07ipmgIMuJggKTXmT4qBSalVVCLFdTKLmYh9ayoLRZNGhddIAzsAvGEfypVhBbWvq+0mgqeMSraUfF7o7jO0QRAVZBBLxXgsbViytfZXHuFDIV/a4PZDZG8LRDIKgF90eDlmNlpyYWXX7Ckwh/g7qkZE9XksDFjhAuke3k82iTQ6N0bBHegJjCKIJSn5o6cspZbV7q/1scLRGn5PPQ+d4cwPy4nw0NMQDMvoTDUYL6Mgig4xLZxUBMXkE=
